export const studentData = [
    {
      id: "STU_00001",
      school_id: "GKP_005",
      Name: "Anuj Sharma",
      Mobile_No: "9876543210",
      Gender: "Male",
      Age: 13,
      Class: 7,
      Section: "B",
      Address: "Plot No-21/47, Geeta Vatika Rd, Shahpur",
      District:"Deoria",
      Pincode: "273014",
      Card_No: "6587-7528-9635-1232",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_1",
      Last_Active_On: "22-Oct",
      Status: "Active",
    },
    {
      id: "STU_00002",
      school_id: "GKP_001",
      Name: "Priya Yadav",
      Mobile_No: "9887766554",
      Gender: "Female",
      Age: 12,
      Class: 6,
      Section: "A",
      Address: "45, Defence Colony, Air Force Station Road",
      District:"Deoria",
      Pincode: "273002",
      Card_No: "8754-9932-1154-6678",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_2",
      Last_Active_On: "17-Oct",
      Status: "Active",
    },
    {
      id: "STU_00003",
      school_id: "GKP_002",
      Name: "Arjun Verma",
      Mobile_No: "9798654321",
      Gender: "Male",
      Age: 10,
      Class: 4,
      Section: "C",
      Address: "72, Jungle Agahi, Near Peepiganj Chowk",
      District:"Deoria",
      Pincode: "273165",
      Card_No: "4458-6623-9123-7765",
      Registered_On_App: "No",
      Parental_Consent_Received: "No",
      Reward_Status: "N/A",
      Last_Active_On: "N/A",
      Status: "Active",
    },
    {
      id: "STU_00004",
      school_id: "GKP_003",
      Name: "Meera Tiwari",
      Mobile_No: "9123456789",
      Gender: "Female",
      Age: 9,
      Class: 3,
      Section: "A",
      Address: "28/4, Jubilee Rd, Buxipur",
      District:"Deoria",
      Pincode: "273001",
      Card_No: "9874-5632-2145-8896",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "N/A",
      Last_Active_On: "30-Sep",
      Status: "Active",
    },
    {
      id: "STU_00005",
      school_id: "GKP_004",
      Name: "Rohit Pandey",
      Mobile_No: "9811122233",
      Gender: "Male",
      Age: 11,
      Class: 5,
      Section: "A",
      Address: "House No 19, Fertilizer Colony Rd",
      District:"Deoria",
      Pincode: "273007",
      Card_No: "6325-7145-3256-4451",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "No",
      Reward_Status: "N/A",
      Last_Active_On: "1-Oct",
      Status: "Inactive",
    },
    {
      id: "STU_00006",
      school_id: "GKP_006",
      Name: "Riya Singh",
      Mobile_No: "9776655443",
      Gender: "Female",
      Age: 14,
      Class: 8,
      Section: "C",
      Address: "11, Kunraghat Main Market Rd",
      District:"Deoria",
      Pincode: "273008",
      Card_No: "1198-6654-8896-2241",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_3",
      Last_Active_On: "18-Oct",
      Status: "Active",
    },
    {
      id: "STU_00007",
      school_id: "GKP_007",
      Name: "Aditya Gupta",
      Mobile_No: "9654412312",
      Gender: "Male",
      Age: 8,
      Class: 2,
      Section: "B",
      Address: "31, Nausar Bazar Rd, GIDA Phase 1",
      District:"Deoria",
      Pincode: "273016",
      Card_No: "7711-5544-6623-9981",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "No",
      Reward_Status: "N/A",
      Last_Active_On: "22-Oct",
      Status: "Active",
    },
    {
      id: "STU_00008",
      school_id: "GKP_008",
      Name: "Kavya Mishra",
      Mobile_No: "9955123499",
      Gender: "Female",
      Age: 13,
      Class: 7,
      Section: "A",
      Address: "54, Raipur Road, Dhudhara Village",
      District:"Deoria",
      Pincode: "273407",
      Card_No: "4496-8877-2233-1455",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_2",
      Last_Active_On: "15-Oct",
      Status: "Inactive",
    },
    {
      id: "STU_00009",
      school_id: "GKP_009",
      Name: "Manav Tripathi",
      Mobile_No: "9822233445",
      Gender: "Male",
      Age: 12,
      Class: 6,
      Section: "C",
      Address: "9, Gauri Manglpur Rd, Near Post Office",
      District:"Deoria",
      Pincode: "273413",
      Card_No: "2244-6699-7711-8855",
      Registered_On_App: "No",
      Parental_Consent_Received: "No",
      Reward_Status: "N/A",
      Last_Active_On: "N/A",
      Status: "Active",
    },
    {
      id: "STU_00010",
      school_id: "GKP_010",
      Name: "Neha Srivastava",
      Mobile_No: "9867543212",
      Gender: "Female",
      Age: 7,
      Class: 2,
      Section: "A",
      Address: "3, Pachowree Village Lane",
      District:"Deoria",
      Pincode: "273212",
      Card_No: "3356-7722-8899-2201",
      Registered_On_App: "No",
      Parental_Consent_Received: "No",
      Reward_Status: "N/A",
      Last_Active_On: "N/A",
      Status: "Active",
    },
    {
      id: "STU_00011",
      school_id: "GKP_005",
      Name: "Aarav Maurya",
      Mobile_No: "9788899001",
      Gender: "Male",
      Age: 6,
      Class: 1,
      Section: "B",
      Address: "12, Akash Vihar, AF Station",
      District:"Deoria",
      Pincode: "273002",
      Card_No: "6654-9923-4578-1147",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_1",
      Last_Active_On: "22-Oct",
      Status: "Active",
    },
    {
      id: "STU_00012",
      school_id: "GKP_001",
      Name: "Sneha Rastogi",
      Mobile_No: "9122298765",
      Gender: "Female",
      Age: 8,
      Class: 2,
      Section: "C",
      Address: "10, Shyam Nagar, AF Colony",
      District:"Deoria",
      Pincode: "273002",
      Card_No: "2254-6644-9977-8851",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_1",
      Last_Active_On: "18-Oct",
      Status: "Active",
    },
    {
      id: "STU_00013",
      school_id: "GKP_002",
      Name: "Harsh Patel",
      Mobile_No: "9711123344",
      Gender: "Male",
      Age: 14,
      Class: 8,
      Section: "B",
      Address: "67, Near Shiv Mandir, Peepiganj",
      District:"Deoria",
      Pincode: "273165",
      Card_No: "9987-4455-2236-1145",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "N/A",
      Last_Active_On: "22-Oct",
      Status: "Active",
    },
    {
      id: "STU_00014",
      school_id: "GKP_003",
      Name: "Muskan Khan",
      Mobile_No: "9833345566",
      Gender: "Female",
      Age: 9,
      Class: 3,
      Section: "A",
      Address: "24, Vindhyavasini Nagar, Buxipur",
      District:"Deoria",
      Pincode: "273001",
      Card_No: "5522-8899-3366-7741",
      Registered_On_App: "No",
      Parental_Consent_Received: "No",
      Reward_Status: "N/A",
      Last_Active_On: "N/A",
      Status: "Active",
    },
    {
      id: "STU_00015",
      school_id: "GKP_004",
      Name: "Yash Rai",
      Mobile_No: "9998877665",
      Gender: "Male",
      Age: 11,
      Class: 5,
      Section: "C",
      Address: "13, Fertilizer Township Rd",
      District:"Deoria",
      Pincode: "273007",
      Card_No: "7744-2266-9911-0045",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_3",
      Last_Active_On: "15-Oct",
      Status: "Active",
    },
    {
      id: "STU_00016",
      school_id: "GKP_006",
      Name: "Tanvi Jaiswal",
      Mobile_No: "9810012233",
      Gender: "Female",
      Age: 10,
      Class: 4,
      Section: "A",
      Address: "56, Kunraghat Colony Lane",
      District:"Deoria",
      Pincode: "273008",
      Card_No: "4477-9955-6633-1122",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "No",
      Reward_Status: "N/A",
      Last_Active_On: "22-Oct",
      Status: "Active",
    },
    {
      id: "STU_00017",
      school_id: "GKP_007",
      Name: "Deepak Chaurasia",
      Mobile_No: "9744412311",
      Gender: "Male",
      Age: 12,
      Class: 6,
      Section: "B",
      Address: "19, Nausar Industrial Area",
      District:"Deoria",
      Pincode: "273016",
      Card_No: "1155-8822-4477-6644",
      Registered_On_App: "No",
      Parental_Consent_Received: "No",
      Reward_Status: "N/A",
      Last_Active_On: "N/A",
      Status: "Inactive",
    },
    {
      id: "STU_00018",
      school_id: "GKP_008",
      Name: "Aditi Verma",
      Mobile_No: "9766234578",
      Gender: "Female",
      Age: 13,
      Class: 7,
      Section: "C",
      Address: "42, Dhudhara Main Street",
      District:"Deoria",
      Pincode: "273407",
      Card_No: "8854-1133-5566-9988",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_3",
      Last_Active_On: "15-Oct",
      Status: "Active",
    },
    {
      id: "STU_00019",
      school_id: "GKP_009",
      Name: "Lakshya Dubey",
      Mobile_No: "9822231199",
      Gender: "Male",
      Age: 14,
      Class: 8,
      Section: "A",
      Address: "78, Chanda Nagar Rd No 2",
      District:"Deoria",
      Pincode: "273413",
      Card_No: "3366-5522-7788-1199",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "N/A",
      Last_Active_On: "18-Oct",
      Status: "Active",
    },
    {
      id: "STU_00020",
      school_id: "GKP_010",
      Name: "Ishika Srivastava",
      Mobile_No: "9111223344",
      Gender: "Female",
      Age: 9,
      Class: 3,
      Section: "B",
      Address: "16, Pachowree Chowk Rd",
      District:"Deoria",
      Pincode: "273212",
      Card_No: "9922-5544-3311-7788",
      Registered_On_App: "Yes",
      Parental_Consent_Received: "Yes",
      Reward_Status: "Milestone_3",
      Last_Active_On: "11-Oct",
      Status: "Active",
    },
]